### ISSUE TITLE
lifx-adapter: TypeError: 'NoneType' object is not subscriptable `

### ISSUE THREAD

**Issue by GoldenbyteGH** [infincia/lifx-adapter#20]
I got these errors during plugin setup

I've installed  the gateway on  a VM with Debian 11

2022-07-04 03:35:21.044 INFO   : Fetching add-on https://github.com/mrstegeman/lifx-adapter/releases/download/v0.5.0/lifx-adapter-0.5.0.tgz as /tmp/SNXmG1/lifx-adapter.tar.gz
2022-07-04 03:35:21.658 INFO   : Expanding add-on /tmp/SNXmG1/lifx-adapter.tar.gz
2022-07-04 03:35:25.332 INFO   : Loading add-on: lifx-adapter
2022-07-04 03:35:27.098 ERROR  : lifx-adapter: Traceback (most recent call last):
2022-07-04 03:35:27.100 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/main.py", line 31, in <module>
2022-07-04 03:35:27.102 ERROR  : lifx-adapter:     _ADAPTER = LifxAdapter(verbose=_DEBUG)
2022-07-04 03:35:27.110 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/pkg/lifx_adapter.py", line 28, in __init__
2022-07-04 03:35:27.112 ERROR  : lifx-adapter:     self.start_pairing(_TIMEOUT)
2022-07-04 03:35:27.114 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/pkg/lifx_adapter.py", line 47, in start_pairing
2022-07-04 03:35:27.116 ERROR  : lifx-adapter:     device = LifxBulb(self, _id, dev)
2022-07-04 03:35:27.118 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/pkg/lifx_device.py", line 57, in __init__
2022-07-04 03:35:27.120 ERROR  : lifx-adapter:     if self.is_color():
2022-07-04 03:35:27.126 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/pkg/lifx_device.py", line 187, in is_color
2022-07-04 03:35:27.128 ERROR  : lifx-adapter:     return bool(self.lifxlan_dev.supports_color())
2022-07-04 03:35:27.130 ERROR  : lifx-adapter:   File "/home/goldenadmin/.webthings/addons/lifx-adapter/lib/lifxlan/device.py", line 386, in supports_color
2022-07-04 03:35:27.134 ERROR  : lifx-adapter:     return self.product_features['color']
2022-07-04 03:35:27.142 ERROR  : lifx-adapter: TypeError: 'NoneType' object is not subscriptable

**Comment by benfrancis** [comment]
FYI https://github.com/WebThingsIO/addon-list/issues/1395#issuecomment-1249582532
